MyWebApp/MyWebApp/Entities/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApp.Entities
{
    public class Game
    {
        public int GameId { get; set; }
        public string GameName { get; set; }
        public string Description { get; set; }
        public int Cost { get; set; }
        public string Image { get; set; } // Имя файла изображения

        // Навигационные свойства
        /// <summary>
        /// Группы игровых жанров (пр., Шутеры, Спортивные и т.д.)
        /// </summary>
        public int GameGroupId { get; set; }
        public GameGroup Group { get; set; }
    }
}

MyWebApp/MyWebApp/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyWebApp.Data;
using MyWebApp.Extensions;
using MyWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApp.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private Cart _cart;
        private string cartKey = "cart";

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }

        public IActionResult Index()
        {
            _cart = HttpContext.Session.Get<Cart>(cartKey);
            return View(_cart.Items.Values);
        }

        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            _cart = HttpContext.Session.Get<Cart>(cartKey);
            var item = _context.Games.Find(id);
            if(item != null)
            {
                _cart.AddToCart(item);
                HttpContext.Session.Set<Cart>(cartKey, _cart);
            }
            return Redirect(returnUrl);
        }

        public IActionResult Delete (int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }
    }
}

MyWebApp/MyWebApp/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyWebApp.Data;
using MyWebApp.Entities;
using MyWebApp.Extensions;
using MyWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApp.Controllers
{
    public class GameController : Controller
    {
        ILogger _logger;
        ApplicationDbContext _context;
        int _pageSize;

        public GameController(ApplicationDbContext context, ILogger<GameController> logger)
        {
            _pageSize = 3;
            _context = context;
            _logger = logger;
        }

        [Route("Catalog")]
        [Route("Catalog/Page_{pageNo}")]
        public IActionResult Index(int? group, int pageNo = 1)
        {
            var groupName = group.HasValue ? _context.GameGroups.Find(group.Value)?.GroupName : "Все";
            _logger.LogInformation($"Info: group={groupName}, page={pageNo}");
            var gamesFiltered = _context.Games.Where(d => !group.HasValue || d.GameGroupId == group.Value);
            ViewData["Groups"] = _context.GameGroups;
            ViewData["CurrentGroup"] = group ?? 0;
            var model = ListViewModel<Game>.GetModel(gamesFiltered, pageNo, _pageSize);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_listpartial", model);
            }
            else
                return View(model);
        }
    }
}

MyWebApp/MyWebApp/Views/Game/Index.cshtml
@model ListViewModel<Game>

@{
    ViewData["Title"] = "Каталог игр";

    var categories = ViewData["Groups"] as IEnumerable<GameGroup>;
    int currentGroup = (int)ViewData["CurrentGroup"];

    var text = currentGroup != 0 ? categories.FirstOrDefault(g => g.GameGroupId == currentGroup)?.GroupName : "Все";
}


<div class="row">
    <div class="col-2">
        <div class="dropdown mt-2">
            <a class="btn btn-secondary dropdown-toggle" asp-action="Index" asp-controller="Game"
               role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-aspopup="true" aria-expanded="false">@text</a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" asp-action="Index" asp-controller="Game">Все</a>
                @foreach (var item in categories)
                {
                    <a class="dropdown-item" asp-action="Index" asp-controller="Game"
                       asp-route-group="@item.GameGroupId" asp-route-pageNo="1">@item.GroupName</a>
                }
            </div>
        </div>
    </div>
</div>
<div class="col-10">
    <div class="card-deck" id="list">
        <partial name="_ListPartial" model="@Model" />
    </div>
    <pager page-current="@Model.CurrentPage" page-total="@Model.TotalPages"
           action="Index" controller="Game" group-id="@currentGroup"></pager>
</div>

MyWebApp/MyWebApp/Views/Game/_ListItemPartial.cshtml
@model Game

<div class="card m-2 p-1 text-center col-4">
    <img src="~/images/@Model.Image" alt="NoImage" class="card-img-top" />
    <div class="card-body">
        <h5 class="card-title">@Model.GameName</h5>
        <p class="card-text">@Model.Description</p>
        <div class="card-text badge badge-secondary">
            <h6>@Model.Cost RUB</h6>
        </div>
        @{ // Получение текущего адреса
            var request = ViewContext.HttpContext.Request;
            var returnUrl = request.Path + request.QueryString.ToUriComponent(); }
        <p class="mt-2">
            <a asp-action="Add" asp-controller="Cart" asp-route-id="@Model.GameId" asp-route-returnUrl="@returnUrl" class="btn btn-primary">
                <i class="fa fa-shopping-cart"></i> В корзину
            </a>
        </p>
    </div>
</div>

MyWebApp/MyWebApp/Views/Game/_ListPartial.cshtml
@model ListViewModel<Game>

@foreach (var item in Model)
{
    <partial name="_ListItemPartial" model="@item" />
}